### ISSUE TITLE
Custom Values (Textbox) & Display as Alertbox

### ISSUE THREAD

**Issue by michaelsboost** [MalcolmDwyer/jquery-ui-nodeEditor#1]
Fiddle: http://liveweave.com/pNpDq4 

Is this still an active project? If so will you please post a tutorial online on how you can make custom nodes like for example what I'm trying to do here?

**Comment by MalcolmDwyer** [comment]
Hi Mike,

I haven't been actively developing this in a while.  If I was building it now, I would definitely drop the jQuery/jQueryUI requirement. But for what's there now, to make the example you posted work better, you would need to get the value of the textfield and use that to resolve the output promise for that node.

```
        fn: function(inputs, properties) {
          var d = $.Deferred();
          var $hello = $("input").val();
          d.resolve($hello);
          return d.promise();
        }
```

Doing that makes it work like I think you want it to... you can put a text node and a display node, connect them, and the display node will show what it receives.  (I notice the textfield is no longer editable once it's in the grid... I'm guessing that's the draggable event handler getting in the way).

**Comment by michaelsboost** [comment]
I been looking for a node editor that I can use to write my jquery code, but there's nothing made yet. After I found this I thought this maybe a good solution. 
(NOTE: I was actually trying to get the alertbox to only show when connected to the display hub) 
However with jquery ui's draggable getting in the way. I think ThreeDubMedia's drag plugin would be a better alternative to integrate. 

I've always wanted to build a node editor, just haven't learned how yet.
